// <auto-generated />
namespace Bas.EuroSing.ScoreBoard.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CreateInitialSchema : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateInitialSchema));
        
        string IMigrationMetadata.Id
        {
            get { return "201801091528359_CreateInitialSchema"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
